# --- Serving options --- #

# GitHub user page settings:
url: "http://pzross.com"
baseurl: ""

# Name of website
title: Phil Ross
subtitle: Evolutionary // Biological // Design

# Short description of your site
description: Computational biologist

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  About: "index"
  Research: "research"
  Contact: "contact"
#  Blog: "blog"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Philipp Ross
  email: "philippross369@gmail.com"
  github: thephilross
  twitter: thephilross
  linkedin: in/philippross
 
# Select which links to show in the footer
footer-links-active:
  email: true
  twitter: true
  github: true
  linkedin: true

#google_analytics: "UA-62544976-1"  

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
paginate: 5
paginate_path: "/blog/page:num/"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
