---
title: "Reads 2018"
output: 
  html_document:
    theme: yeti
    highlight: textmate
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

<!-- The file chunks.R contains chunks that define default settings -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, include=FALSE, echo=FALSE, results='asis'}
```

<!-- packages -->
```{r packages, echo=FALSE, include=FALSE}
```

<!-- custom defined functions -->
```{r custom-functions, echo=FALSE}
```

Stuff I read in 2018.

## Animals

### Dolphins are smarter than you know

https://www.theguardian.com/environment/2014/jun/08/the-dolphin-who-loved-me

https://www.theguardian.com/science/2003/jul/03/research.science