---
title: "Reads"
output: 
  html_document:
    theme: yeti
    highlight: textmate
    toc: false
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

<!-- The file chunks.R contains chunks that define default settings -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, include=FALSE, echo=FALSE, results='asis'}
```

<!-- packages -->
```{r packages, echo=FALSE, include=FALSE}
```

<!-- custom defined functions -->
```{r custom-functions, echo=FALSE}
```

The readings I would like to remember and come back to from time to time.

[The bus ticket theory of genius](http://www.paulgraham.com/genius.html)

A trilogy on human genetics:  

* [Our vast, shared family tree](https://gcbias.org/2017/11/20/our-vast-shared-family-tree/)  
* [Your ancestors lived all over the world](https://gcbias.org/2017/11/28/your-ancestors-lived-all-over-the-world/)  
* [Where did your genetic ancestors come from?](https://gcbias.org/2017/12/19/1628/)  

